version: "3.8"

services:
  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge
